version: '3.6'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user_admin
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=administration

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - '.:/code'
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=pGclgg90mfog3mw0zHot6t2XSp08Yuqedq2t48mibrdvamj7il
      - POSTGRES_USER=user_admin
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=administration
      - POSTGRES_HOST=db
      - GOOGLE_OAUTH_CLIENT_ID=1011921308676-083akj9o1kedln7rnblfan7af0j6rhnq.apps.googleusercontent.com
      - GOOGLE_OAUTH_CLIENT_SECRECT=IX-rVo9QRaqnfrdjKnZl-eeu
    depends_on:
      - db
    restart: on-failure

volumes:
  postgres_data:
